### ISSUE TITLE
Running deploy.sh dev in Athena Console.

### ISSUE THREAD

**Issue by noam-elbaz** [JaderDias/download-from-common-crawl#1]
Hi @JaderDias 

I'm new to AWS and managing Cloud Infrastructure.

I signed up for Athena AWS.  I cloned the project to the new AWS directory.  

and then tried to run "deploy.sh dev" and nothing happened.  Any intro tutorials you could send me to, to get me a quick start?  

What basics do I need to learn to start working through your tutorial / guide.

(Sorry for the noob questions)

Thanks

**Comment by JaderDias** [comment]
Hello Noam, I want to make my instructions as noob friendly as possible. I don't know all the steps I took to make it work in my environment that are missing in yours.

Could you share your operating system and whether terraform is installed?

Don't you see any error message at all?

**Comment by noam-elbaz** [comment]
Mac OS. 
and yes - I followed the Terrafrom "get started" 
Everything worked fine.

<img width="549" alt="image" src="https://user-images.githubusercontent.com/47975228/177552977-8d22ba00-9d4b-4bb5-b381-134a820bd2c2.png">

**Comment by JaderDias** [comment]
I can try to port it to Mac later. But if you can't wait you can try on a Linux box, Amazon cloud console or even Google cloud shell. They're more similar to the environment that I used to test it

**Comment by noam-elbaz** [comment]
Ok.  Getting closer.  

1. cloned the project.  
2. went into the terraform project folder
3. terraform login / init / plan 
4. then I'm up to this part....
<img width="849" alt="image" src="https://user-images.githubusercontent.com/47975228/177555320-085ddb3f-7da7-4f87-b638-f2ba48690d8c.png">
5. updated main.tf according to suggestion....  but no go.

**Comment by JaderDias** [comment]
I think i forgot to include 'aws login' on the instructions or something similar. I don't recall the the method i used to authenticate

**Comment by noam-elbaz** [comment]
> I can try to port it to Mac later. But if you can't wait you can try on a Linux box, Amazon cloud console or even Google cloud shell. They're more similar to the environment that I used to test it

No stress. If you don't mind porting to Mac at some point, would be great.  Meanwhile, I'll try the Amazon or Google Shell.

**Comment by JaderDias** [comment]
https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

**Comment by JaderDias** [comment]
Resolved with https://github.com/JaderDias/download-from-common-crawl/commit/468f956f52271d1d32ee7d151128849333b515ac
